### ISSUE TITLE
Update specification license to Community Specification License 1.0

### ISSUE THREAD

**Issue by idunbarh** [SBOMit/specification#13]
LF started IP/license review of the SBOMit spec and provided feedback that the SBOMit specification needs to be Community Specification License 1.0 licensed per the OpenSSF charter (Section 5, Page 9):
https://cdn.platform.linuxfoundation.org/agreements/openssf.pdf

**Comment by JustinCappos** [comment]
So there was a big issue with this early on (with people strongly arguing
we should avoid the OpenSSF) because Apple and other companies don't like
the CSL 1.0.  We heard from David Wheeler and a few others that they would
approve "a reasonable license" and that their charter wasn't meant to
exclude, but to include a default.

So, please put me in touch with folks and I can escalate to straighten this
out, if need be.

**Comment by JustinCappos** [comment]
Okay, I replied there.  Let's see how it goes!

**Comment by jeffcshapiro** [comment]
Let's wait and not update the license yet until we resolve the issue of which license is best for you, and see if an exception has been / will be granted if you stay with CC-BY-4.0.

**Comment by JustinCappos** [comment]
Okay, from our community standpoint, the license that the CNCF uses (see clause 11f https://github.com/cncf/foundation/blob/main/charter.md ) is what several community members are strongly in favor of.  So, this is what is best for us.  

@jeffcshapiro Are you able to approve this license or if not, can you escalate this to someone who can?

**Comment by jeffcshapiro** [comment]
Understood.  Keep in mind the CNCF charter is referring to documentation, not a specification.

It's not up to me, most likely the OpenSSF governing board makes the decision.  I will follow up with Amanda @hythloda and anyone else necessary to help get this resolved.
